name: Deploy Preview Docs

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"
      - "*.md"
      - "*.adoc"
      - "*.txt"
      - ".all-contributorsrc"
  pull_request:
    paths-ignore:
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"
      - "*.md"
      - "*.txt"
      - ".all-contributorsrc"
jobs:
  build-website:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: "maven"

      - name: Build with Maven
        run: mvn -B formatter:validate impsort:check verify --file pom.xml -DskipTests
      - name: Publishing to surge for preview
        id: deploy
        run: npx surge ./docs/target/generated-docs/ --domain https://quarkus-roq-preview-pr-${{  github.event.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      - name: Update PR status comment on success
        uses: actions-cool/maintain-one-comment@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            🎊 PR Preview ${{ github.sha }} has been successfully built and deployed. See the documentation preview: https://quarkus-roq-preview-pr-${{ github.event.number }}.surge.sh
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.pr.outputs.id }}
          emojis: "heart"
      - name: Update PR status comment on failure
        if: ${{ failure() }}
        uses: actions-cool/maintain-one-comment@v3.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            😭 Deploy PR Preview failed.
            <img width="300" src="https://user-images.githubusercontent.com/507615/90250824-4e066700-de6f-11ea-8230-600ecc3d6a6b.png">
            <!-- Sticky Pull Request Comment -->
          body-include: "<!-- Sticky Pull Request Comment -->"
          number: ${{ steps.pr.outputs.id }}
          emojis: "confused"
