name: Surge.sh Preview

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write # Required to update PR status comment
    steps:
      - name: Download PR Artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Download PR ID Artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-id
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Store PR id as variable
        id: pr
        run: |
          echo "id=$(<pr-id.txt)" >> $GITHUB_OUTPUT
          rm -f pr-id.txt

      - name: Publishing docs to surge for preview
        id: deploy
        run: npx surge ./ --domain https://quarkiverse-roq-pr-${{ steps.pr.outputs.id }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Update PR status comment on success (docs)
        uses: quarkusio/action-helpers@main
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            🚀 PR Preview ${{ github.sha }} has been successfully built and deployed to https://quarkiverse-roq-pr-${{ steps.pr.outputs.id }}-preview.surge.sh
          body-marker: <!-- Preview status comment marker -->

      - name: Update PR status comment on failure
        uses: quarkusio/action-helpers@main
        if: ${{ failure() }}
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            😭 Deploy PR Preview failed.
          body-marker: <!-- Preview status comment marker -->

      - name: Publishing blog to surge for preview
        id: deploy-blog
        run: npx surge ./ --domain https://quarkiverse-roq-blog-pr-${{ steps.pr.outputs.id }}-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}

      - name: Update PR status comment on success (blog)
        uses: quarkusio/action-helpers@main
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            🚀 PR Preview ${{ github.sha }} has been successfully built and deployed to https://quarkiverse-roq-pr-${{ steps.pr.outputs.id }}-preview.surge.sh
          body-marker: <!-- Preview status comment marker -->

      - name: Update PR status comment on failure
        uses: quarkusio/action-helpers@main
        if: ${{ failure() }}
        with:
          action: maintain-one-comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ steps.pr.outputs.id }}
          body: |
            😭 Deploy PR Preview failed.
          body-marker: <!-- Preview status comment marker -->
